[workspace]
authors = ["Yu-An Chen <atwood12@gmail.com>"]
channels = ["conda-forge"]
name = "quick-look-env"
platforms = ["osx-arm64", "win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.10.*"
openjdk = "21.*"

[pypi-dependencies]
quick-look = { git = "https://github.com/Yu-AnChen/quick-look.git" }
